title: memo
email: your-email@example.com
description: メモ
baseurl: /memo
url: https://shmz.github.io
encoding: utf-8

permalink: /posts/:year-:month-:day-:title.html
timezone: Asia/Tokyo

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile']

feed:
  path: atom.xml
